---
# catalog
catalog_ckan_allow_login_routes: true
catalog_ckan_app_version: bionic
catalog_ckan_db_host: "{{ catalog_postgresql_login_host }}"
catalog_ckan_db_name: ckan
catalog_ckan_db_pass: "{{ vault_catalog_ckan_db_pass }}"
catalog_ckan_db_user: ckan
catalog_ckan_redis_host: catalog-harvester1tf.internal.bionic.datagov.us
catalog_ckan_redis_pass: "{{ vault_catalog_ckan_redis_pass }}"
catalog_ckan_service_url: https://catalog.bionic.datagov.us
catalog_ckan_solr_host: datagov-solr1tf.internal.bionic.datagov.us
catalog_ckan_solr_port: "{{ solr_port }}"
catalog_postgresql_login_host: "{{ vault_catalog_postgresql_login_host }}"
catalog_postgresql_login_password: "{{ vault_catalog_postgresql_login_password }}"
catalog_postgresql_login_user: "{{ vault_catalog_postgresql_login_user }}"
catalog_pycsw_db_host: "{{ catalog_postgresql_login_host }}"
catalog_pycsw_db_name: pycsw
catalog_pycsw_db_pass: "{{ vault_catalog_pycsw_db_pass }}"
catalog_pycsw_db_user: pycsw
catalog_db_pass: "{{ catalog_ckan_db_pass }}"
catalog_db_name: "{{ catalog_ckan_db_name }}"
catalog_db_user: "{{ catalog_ckan_db_user }}"

# common
common_newrelic_enabled: false
common_python_version_number: 2.7.16
filebeat_enabled: false
nessus_agent_enabled: false
trendmicro_enabled: false


# dashboard
# hostname needed for smoke test, IP address needed for ALB health check
dashboard_nginx_server_name: dashboard.bionic.datagov.us $hostname {{ ansible_default_ipv4.address }}
dashboard_service_url: https://dashboard.bionic.datagov.us


datagov_enable_postgresql_role: true
datagov_environment: bionic


default_tls_host_key: "{{ vault_default_tls_host_key }}"
default_tls_host_certificate: |-
  -----BEGIN CERTIFICATE-----
  MIIEZjCCA06gAwIBAgIJAOYrtazOX0ojMA0GCSqGSIb3DQEBCwUAMIHHMQswCQYD
  VQQGEwJVUzELMAkGA1UECAwCREMxEzARBgNVBAcMCldhc2hpbmd0b24xKDAmBgNV
  BAoMH0dlbmVyYWwgU2VydmljZXMgQWRtaW5pc3RyYXRpb24xKjAoBgNVBAsMIVRl
  Y2hub2xvZ3kgVHJhbnNmb3JtYXRpb24gU2VydmljZTEcMBoGA1UEAwwTKi5iaW9u
  aWMuZGF0YWdvdi51czEiMCAGCSqGSIb3DQEJARYTZGF0YWdvdmhlbHBAZ3NhLmdv
  djAeFw0xOTAzMjkyMzQyMjNaFw0yMDAzMjgyMzQyMjNaMIHHMQswCQYDVQQGEwJV
  UzELMAkGA1UECAwCREMxEzARBgNVBAcMCldhc2hpbmd0b24xKDAmBgNVBAoMH0dl
  bmVyYWwgU2VydmljZXMgQWRtaW5pc3RyYXRpb24xKjAoBgNVBAsMIVRlY2hub2xv
  Z3kgVHJhbnNmb3JtYXRpb24gU2VydmljZTEcMBoGA1UEAwwTKi5iaW9uaWMuZGF0
  YWdvdi51czEiMCAGCSqGSIb3DQEJARYTZGF0YWdvdmhlbHBAZ3NhLmdvdjCCASIw
  DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKiV0g2WLzjeqJQHQAQ7XRPcIosL
  NJGydkJB16A47rbaaNQbVPHCCK98sqkKrzWs76aQALC3kMwfoc43phzrfAMxMdMr
  oRW+GhLD70Lmpwmu10eTVXl1gAIoV0e6Gz+Praqnp7mDgujOMT5QCitZ4HBhOmYC
  rx9tDRODpIB/rt2n05GBjz+dhOvvOiPIT+e3Up3fnJqXjMnlDwbDZwa8CUG8CC30
  oqeCesDdudJVPbKKXlxFTgG7EQTtojQj/dKhr8ONYeqTF1kTeDRcjRCcNtWecrbO
  +pf+Qpth0qPEmhW+ULBu39MdpQbqwDONTrHZ7gc5oN4q7CwImkEouLGYA8MCAwEA
  AaNTMFEwHQYDVR0OBBYEFE3d1KTCu14ig3GIq5P/3HL2I2trMB8GA1UdIwQYMBaA
  FE3d1KTCu14ig3GIq5P/3HL2I2trMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcN
  AQELBQADggEBAG+O6zUGChbYZWEwQsoYnKnPfOMv5lSQeQB2W9IvXjSJxc2/boS9
  E6f23btIDU6CoEEt2nMNBbP21zrYs8VPlRxF1Pg16m6+3xLNIGDC6QE9Qnr6ZrGf
  k0ELtL/xj7oJyHl97kI4nnadKiHhL5MvvQoNU4xES2xjfGZNKI1BPAxS4kptXI8K
  LKNb5EXDq5ujKp0pdbvQAJoN3FSD1kCc4EgCtJnRRW8JFQOq0R7L9LZX9dWwPu+N
  yVzn1bzmlCV6AQmC2rcaBQpunJzn5bZ3BSDzrorwXodLmAh9Rt44H0Q8agRZFtb3
  Bbue8FC5sfTkY70oq6O17iUyTx0hgbDbm78=
  -----END CERTIFICATE-----


jumpbox_operators: "{{ datagov_operators_test }}"


inventory_app_repo_branch: bionic
inventory_ckan_service_url: https://inventory.bionic.datagov.us
inventory_ckan_solr_port: "{{ solr_port }}"

pycsw_app_version: datagov/v2.4.x
pycsw_base_url: https://catalog.bionic.datagov.us
pycsw_catalog_url: https://catalog.bionic.datagov.us
pycsw_db_host: "{{ catalog_pycsw_db_host }}"
pycsw_db_name: "{{ catalog_pycsw_db_name }}"
pycsw_db_password: "{{ catalog_pycsw_db_pass }}"
pycsw_db_user: "{{ catalog_pycsw_db_user }}"


# public urls
urls_public:
  catalog: https://catalog.bionic.datagov.us
urls_private:
  catalog: https://catalog.bionic.datagov.us

ckan_site_domain: "{{ urls_public.catalog }}"

nrinfragent_license_key: "{{ vault_nrinfragent_license_key }}"


# solr
solr_master_server: datagov-solr1tf.internal.bionic.datagov.us
solr_java_packages:
  - openjdk-8-jdk


# List of CodeIgniter pre-approved admin emails
codeigniter_pre_approved_admins: "{{ vault_codeigniter_pre_approved_admins }}"

# App environment
web_app_env: production
real_ansible_env: production

# postfix
postfix_relayhost: smtp.gsa.gov
postfix_relayhost_port: 25
postfix_sasl_auth_enable: false
postfix_relaytls: true
default_email_from: no-reply@datagov.us
postfix_key: "{{ default_tls_host_key }}"
postfix_pem: "{{ default_tls_host_certificate }}"

# SAML
saml2_idp_entry: login.test.max.gov
saml2_idp_metadata_url: "https://{{ saml2_idp_entry }}/idp/shibboleth"
saml_idp_cert_fprint: "7A43DACB95D67FB6A804FD37C8A7DCA5B0384939"
saml2_sp_public_certificate: "{{ default_tls_host_certificate }}"
saml2_sp_private_key: "{{ default_tls_host_key }}"


# ckan
# Auth cookie `auth_tkt` must be HTTPS-only (SECURE) on Production
who_secure: True

# wordpress
# hostname needed for smoke test, IP address needed for ALB health check
wordpress_nginx_server_name: wordpress.bionic.datagov.us $hostname {{ ansible_default_ipv4.address }}
wordpress_service_url: https://wordpress.bionic.data.gov
