---
datagov_service: catalog

catalog_app_type: worker
catalog_ckan_db_host: "{{ vault_catalog_ckan_db_host }}"
catalog_ckan_db_name: "{{ vault_catalog_ckan_db_name }}"
catalog_ckan_db_pass: "{{ vault_catalog_ckan_db_pass }}"
catalog_ckan_db_user: "{{ vault_catalog_ckan_db_user }}"
catalog_pycsw_db_host: "{{ vault_catalog_pycsw_db_host }}"
catalog_pycsw_db_name: "{{ vault_catalog_pycsw_db_name }}"
catalog_pycsw_db_pass: "{{ vault_catalog_pycsw_db_pass }}"
catalog_pycsw_db_user: "{{ vault_catalog_pycsw_db_user }}"

# project path
project_source_rollback_path: /usr/lib/ckan-rollback
project_source_new_code_path: /usr/lib/ckan-new
current_source_symlink: /usr/lib/ckan
project_index_path: /usr/lib/ckan

# db credentials
ckan_db_server: "{{ vault_ckan_db_server }}"
catalog_db_user: "{{ vault_catalog_db_user }}"
catalog_db_pass: "{{ vault_catalog_db_pass }}"
catalog_db_name: "{{ vault_catalog_db_name }}"

# other
catalog_ckan_redis_host: catalog-harvester1d.dev-ocsit.bsp.gsa.gov
catalog_ckan_solr_host: datagov-solrm1d.dev-ocsit.bsp.gsa.gov
env: local
redis_password: "{{ vault_redis_pass }}"

# max login
saml2_site_url: https://admin-catalog-datagov.dev-ocsit.bsp.gsa.gov/

# secrets
catalog_ckan_who_ini_secret: "{{ vault_who_ini_secret }}"
ckan_instance_secret: "{{ vault_ckan_instance_secret }}"
ckan_instance_uuid: "{{ vault_ckan_instance_secret }}"

# token_dat for Google Analytics
token_dat: "{{ vault_token_dat }}"

# Trendmicro firewall policy
trendmicro_policy_id: "{{ trendmicro_policy_id_app }}"
