---
- name: Catalog web stack
  hosts: catalog-web
  serial: 1
  vars:
      app_type: catalog

  roles:
    - role: software/common/tls
      tags:
        - tls
    - role: software/ckan/common
    - role: gsa.datagov-deploy-apache2
      apache2_enabled: "{{ datagov_in_service | default(true) }}"
      tags:
        - apache
    - role: software/ckan/catalog/ckan-app
      vars:
        app_repo_branch: "{{ catalog_ckan_app_version }}"
      tags:
        - app-deploy
    - role: software/ckan/fix-ckan-tracking
      tags:
        - frontend

  # Host-level smoke tests
  tasks:
    - name: flush handlers
      meta: flush_handlers

    - name: assert catalog is up
      uri:
        url: http://{{ ansible_fqdn }}/api/action/status_show
        follow_redirects: none
        status_code: 200
        # TODO enable cert validation. Staging and production hosts have GSA
        # signed certs which should be valid.
        # https://github.com/GSA/datagov-deploy/issues/900
        validate_certs: false
        headers:
          # For catalog-admin hosts
          Cookie: auth_tkt=1
      retries: 3
      delay: 10
      register: result
      until: not result.failed
      when: datagov_in_service | default(true)


- name: logrotate configuration
  hosts: catalog-web
  roles:
    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: inventory
          paths:
            - /var/log/ckan/ckan.error.log
            - /var/log/ckan/ckan.access.log
          options:
            - compress
            - copytruncate
            - size 512M
            - missingok
            - rotate 8


- name: NewRelic
  hosts: catalog-web,!catalog-admin
  vars:
    newrelic_app_name: catalog
  roles:
    - monitoring/newrelic/python-agent-ansible

- name: NewRelic
  hosts: catalog-admin
  vars:
    newrelic_app_name: catalog-admin
  roles:
    - monitoring/newrelic/python-agent-ansible


- name: Service-level smoke tests
  hosts: catalog-web
  tasks:
    - name: flush handlers
      meta: flush_handlers

    - name: assert catalog is up
      uri:
        url: "{{ catalog_ckan_service_url }}/api/action/status_show"
        follow_redirects: none
        status_code: 200
        # TODO enable cert validation. Staging and production hosts have GSA
        # signed certs which should be valid.
        # https://github.com/GSA/datagov-deploy/issues/900
        validate_certs: false
      run_once: true
      delegate_to: localhost
