---
- name: Provisioning Inventory CKAN Stack
  hosts: inventory-web
  serial: 1
  vars:
    app_type: inventory

  roles:
    - {role: software/common/tls, tags: ['tls']}
    - software/ckan/common
    - role: gsa.datagov-deploy-apache2
      apache2_enabled: datagov_in_service | default(true)
      tags: apache
    - {role: software/ckan/inventory, tags: ['deploy']}
    - {role: software/ckan/saml2, tags: ['saml2']}

  # Host-level smoke tests
  tasks:
    - name: flush handlers
      meta: flush_handlers

    - name: assert datapusher is up
      uri:
        url: http://localhost:8800
        follow_redirects: none
        status_code: 200
        validate_certs: false
      retries: 3
      delay: 10
      register: result
      until: not result.failed
      when: datagov_in_service | default(true)

    - name: assert app is up
      uri:
        url: http://{{ ansible_fqdn }}/api/action/status_show
        follow_redirects: none
        status_code: 200
        # TODO enable cert validation. Staging and production hosts have GSA
        # signed certs which should be valid.
        # https://github.com/GSA/datagov-deploy/issues/900
        validate_certs: false
      retries: 3
      delay: 10
      register: result
      until: not result.failed
      when: datagov_in_service | default(true)


- name: logrotate configuration
  hosts: inventory-web
  roles:
    - role: nickhammond.logrotate
      logrotate_scripts:
        - name: inventory
          paths:
            - /var/log/inventory/*.log
          options:
            - compress
            - copytruncate
            - weekly
            - missingok
            - rotate 8


- name: NewRelic
  hosts: inventory-web
  vars:
    newrelic_app_name: inventory
  roles:
    - monitoring/newrelic/python-agent-ansible
  tags:
    - newrelic


- name: Service-level smoke tests
  hosts: inventory-web
  tasks:
    - name: flush handlers
      meta: flush_handlers

    - name: assert inventory service is available
      uri:
        url: "{{ inventory_ckan_service_url }}/api/action/status_show"
        follow_redirects: none
        status_code: 200
        # TODO enable cert validation. Staging and production hosts have GSA
        # signed certs which should be valid.
        # https://github.com/GSA/datagov-deploy/issues/900
        validate_certs: false
        headers:
          # Avoid login redirect
          Cookie: auth_tkt=1
      run_once: true
      delegate_to: localhost
      retries: 3
      delay: 10
      register: result
      until: not result.failed
