---
- name: reload apache2
  service: name=apache2 state=reloaded
  when:
    - catalog_app_type == "web"
    - datagov_in_service | default(true)

- name: reload supervisor
  command: supervisorctl reload
  when:
    - catalog_app_type == "worker"
    - datagov_in_service | default(true)
  tags:
    - skip_ansible_lint
