---
- name: Converge
  hosts: all
  roles:
    - role: ckan-app
      vars:
        catalog_ckan_who_ini_secret: e45cfed3-40f1-41c0-8e92-77eda7ddd9f3
        catalog_app_type: worker
        catalog_ckan_worker_type: main_worker
        catalog_harvest_enable_harvest_report: true
